"""
best_model_inference.py  —  EfficientNetB3  (auto-generated by compare_models.py)
═══════════════════════════════════════════════════════════════════
Winner selection:  composite = 0.35×Accuracy + 0.4×Macro-F1 + 0.25×ROC-AUC

  composite score : 0.9169
  accuracy        : 0.8925
  macro F1        : 0.8900
  ROC-AUC         : 0.9943
  speed           : 42.01 ms / image

Quick usage
-----------
  from best_model_inference import SolarPanelClassifier
  clf = SolarPanelClassifier()
  print(clf.predict("panel.jpg"))
"""

import torch
import torch.nn as nn
import numpy as np
from torchvision import transforms, models as tv_models
from PIL import Image

CLASSES  = ['Bird-drop', 'Clean', 'Dusty', 'Electrical-damage', 'Physical-Damage', 'Snow-Covered']
CKPT     = r"models/efficientnet_b3.h5"
_DEVICE  = torch.device("cuda" if torch.cuda.is_available() else "cpu")

_TF = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])


class SolarPanelClassifier:
    """Production-ready inference wrapper for EfficientNetB3."""

    def __init__(self, device=_DEVICE):
        self.device  = device
        self.classes = CLASSES
        self.model   = self._load()
        print(f"  ✔ {self.__class__.__name__} ready on {device}")

    def _load(self):
    enet = tv_models.efficientnet_b3(weights=None)
    in_f = enet.classifier[1].in_features
    enet.classifier = nn.Sequential(nn.Dropout(0.4), nn.Linear(in_f, 6))
    model = enet.to(device)
    model.load_state_dict(torch.load(r'models/efficientnet_b3.h5', map_location=device))
        model.eval()
        return model

    @torch.no_grad()
    def predict(self, image_path: str) -> dict:
        """
        Classify one image.

        Returns
        -------
        dict
            predicted_class : str
            confidence      : float  (0–1)
            probabilities   : dict[class_name → float]
        """
        img   = Image.open(image_path).convert("RGB")
        inp   = _TF(img).unsqueeze(0).to(self.device)
        probs = torch.softmax(self.model(inp), dim=1).squeeze().cpu().numpy()
        idx   = int(np.argmax(probs))
        return {
            "predicted_class": self.classes[idx],
            "confidence"     : float(probs[idx]),
            "probabilities"  : {c: round(float(p), 4)
                                for c, p in zip(self.classes, probs)},
        }

    @torch.no_grad()
    def predict_batch(self, paths: list) -> list:
        """Classify a list of image paths. Returns list of dicts."""
        return [self.predict(p) for p in paths]

    def predict_with_bar(self, image_path: str):
        """Predict and print a bar-chart summary to stdout."""
        out = self.predict(image_path)
        print(f"\n  Image     : {image_path}")
        print(f"  Predicted : {out['predicted_class']}")
        print(f"  Confidence: {out['confidence']*100:.2f}%")
        print("  ─" * 25)
        for cls, prob in sorted(out["probabilities"].items(),
                                key=lambda x: -x[1]):
            bar = "█" * int(prob * 30)
            print(f"  {cls:<24} {prob:.4f}  {bar}")
        return out


# ── CLI smoke-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python best_model_inference.py <image_path>")
        sys.exit(1)
    clf = SolarPanelClassifier()
    clf.predict_with_bar(sys.argv[1])
